# https://github.com/knojector/SteamAuthenticationBundle for configuration documentation
knojector_steam_authentication:
    api_key: "%env(STEAM_API_KEY)%"
    login_route: 'login_check'
    login_redirect: 'login_redirect'
    user_class: App\Entity\User
