# https://github.com/knojector/SteamAuthenticationBundle for configuration documentation
knojector_steam_authentication:
    login_success_redirect: 'loginRedirect'
    login_failure_redirect: 'loginFailure'
