twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        navbar: '@App\Service\NavbarService'
        configService: '@App\Service\ConfigService'
        predictionService: '@App\Service\PredictionService'
    exception_controller: null

when@test:
    twig:
        strict_variables: true
