name: vidya-gaem-awards
recipe: symfony
config:
  webroot: public
  php: '8.1'
  via: apache:2.4
  database: mysql:8.0
  xdebug: true

services:
  appserver:
    overrides:
      environment:
        # Support debugging CLI with XDEBUG.
        PHP_IDE_CONFIG: "serverName=lando"
        XDEBUG_SESSION_START: lando
