VGA\Model\GameRelease:
  type: entity
  table: game_releases
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 100
    notable:
      type: boolean
      nullable: false
    pc:
      type: boolean
      nullable: false
    ps3:
      type: boolean
      nullable: false
    ps4:
      type: boolean
      nullable: false
    vita:
      type: boolean
      nullable: false
    psn:
      type: boolean
      nullable: false
    x360:
      type: boolean
      nullable: false
    xb1:
      type: boolean
      nullable: false
    xbla:
      type: boolean
      nullable: false
    wii:
      type: boolean
      nullable: false
    wiiu:
      type: boolean
      nullable: false
    wiiware:
      type: boolean
      nullable: false
    n3ds:
      type: boolean
      nullable: false
    ouya:
      type: boolean
      nullable: false
    mobile:
      type: boolean
      nullable: false
