VGA\Model\Nominee:
  type: entity
  table: nominees
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    shortName:
      type: string
      nullable: false
      length: 45
    name:
      type: string
      nullable: false
      length: 100
    subtitle:
      type: string
      nullable: false
      length: 255
    image:
      type: string
      nullable: false
      length: 255
    flavorText:
      type: text
      nullable: false
  manyToOne:
    award:
      targetEntity: Award
      inversedBy: nominees
      joinColumn:
        name: awardID
        referencedColumnName: id
