VGA\Model\UserNomination:
  type: entity
  table: user_nominations
  id:
    id:
      type: integer
      nullable: false
      generator:
        strategy: AUTO
  fields:
    user:
      type: string
      nullable: false
      length: 45
    nomination:
      type: string
      nullable: false
      length: 255
    timestamp:
      type: datetime
      nullable: false
  manyToOne:
    award:
      targetEntity: Award
      inversedBy: userNominations
      joinColumn:
        name: categoryID
        referencedColumnName: id
