VGA\Model\UserVotingCode:
  type: entity
  table: user_voting_codes
  id:
    code:
      type: string
      nullable: false
      length: 100
    cookieID:
      type: string
      nullable: false
      length: 255
  fields:
    referer:
      type: text
      nullable: true
