VGA\Model\VotingCodeLog:
  type: entity
  table: voting_code_logs
  id:
    id:
      type: integer
      nullable: false
      generator:
        strategy: AUTO
  fields:
    cookieID:
      type: string
      nullable: false
      length: 255
    timestamp:
      type: datetime
      nullable: false
    ip:
      type: string
      nullable: false
      length: 45
    code:
      type: string
      nullable: false
      length: 20
    referer:
      type: string
      length: 255
      nullable: true
  manyToOne:
    user:
      targetEntity: User
      nullable: true
      inversedBy: votes
      joinColumn:
        name: userID
        referencedColumnName: steamID
