VGA\Model\Action:
  type: entity
  table: actions
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    user:
      type: string
      nullable: false
      length: 45
    timestamp:
      type: datetime
      nullable: false
    page:
      type: string
      nullable: false
      length: 30
    action:
      type: string
      nullable: false
      length: 40
    data1:
      type: string
      nullable: true
      length: 50
    data2:
      type: string
      nullable: true
      length: 50
