VGA\Model\Vote:
  type: entity
  table: votes
  options:
    collate: utf8mb4_unicode_ci
    charset: utf8mb4
  id:
    cookieID:
      type: string
      nullable: false
      length: 191
    award:
      associationKey: true
  fields:
    preferences:
      type: json_array
      nullable: false
    timestamp:
      type: datetime
      nullable: false
    ip:
      type: string
      nullable: false
      length: 45
    votingCode:
      type: string
      nullable: true
      length: 20
    number:
      type: integer
      nullable: true
  manyToOne:
    award:
      targetEntity: Award
      nullable: false
      inversedBy: votes
      joinColumn:
        name: awardID
        referencedColumnName: id
    user:
      targetEntity: User
      nullable: true
      inversedBy: votes
      joinColumn:
        name: userID
        referencedColumnName: steamID
