VGA\Model\Autocompleter:
  type: entity
  table: autocompleters
  id:
    id:
      type: string
      length: 30
  fields:
    name:
      type: string
      nullable: false
      length: 20
    strings:
      type: json_array
      nullable: false
