AppBundle\Entity\Access:
  type: entity
  table: access
  options:
    collate: utf8mb4_unicode_ci
    charset: utf8mb4
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    cookieID:
      type: string
      nullable: false
      length: 255
    timestamp:
      type: datetime
      nullable: false
    page:
      type: string
      nullable: false
      length: 30
    requestString:
      type: string
      nullable: false
      length: 255
    requestMethod:
      type: string
      nullable: false
      length: 4
    ip:
      type: string
      nullable: false
      length: 45
    userAgent:
      type: string
      nullable: false
      length: 255
    filename:
      type: string
      nullable: false
      length: 255
    referer:
      type: string
      nullable: true
      length: 255
  manyToOne:
    user:
      targetEntity: AppBundle\Entity\User
      nullable: true
      joinColumn:
        name: userID
        referencedColumnName: steamID
        nullable: true
