AppBundle\Entity\Advertisement:
  type: entity
  table: advertisements
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      nullable: false
    link:
      type: string
      nullable: false
    image:
      type: string
      nullable: true
    special:
      type: boolean
      nullable: false
