AppBundle\Entity\AwardFeedback:
  type: entity
  table: award_feedback
  options:
    collate: utf8mb4_unicode_ci
    charset: utf8mb4
  id:
    award:
      associationKey: true
    user:
      type: string
      nullable: false
      length: 45
  fields:
    opinion:
      type: smallint
      nullable: false
  manyToOne:
    award:
      targetEntity: Award
      inversedBy: feedback
      joinColumn:
        name: awardID
        referencedColumnName: id
