AppBundle\Entity\Config:
  type: entity
  table: config
  options:
    collate: utf8mb4_unicode_ci
    charset: utf8mb4
  id:
    id:
      type: string
      nullable: false
      length: 30
  fields:
    votingStart:
      type: datetime
      nullable: true
    votingEnd:
      type: datetime
      nullable: true
    streamTime:
      type: datetime
      nullable: true
    defaultPage:
      type: string
      nullable: false
      length: 30
    publicPages:
      type: json_array
      nullable: false
    readOnly:
      type: boolean
      nullable: false
    timezone:
      type: string
      length: 50
      nullable: false
