AppBundle\Entity\InventoryItem:
  type: entity
  table: inventory_items
  id:
    id:
      type: integer
      nullable: false
      generator:
        strategy: AUTO
  fields:
    shortName:
      type: string
      nullable: false
      length: 50
    name:
      type: string
      nullable: false
      length: 50
    rarity:
      type: integer
      nullable: false
    image:
      type: string
      nullable: true
