AppBundle\Entity\News:
  type: entity
  table: news
  options:
    collate: utf8mb4_unicode_ci
    charset: utf8mb4
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    headline:
      type: string
      nullable: true
      length: 255
    text:
      type: text
      nullable: false
    timestamp:
      type: datetime
      nullable: false
    visible:
      type: boolean
      nullable: false
  manyToOne:
    user:
      targetEntity: AppBundle\Entity\User
      joinColumn:
        name: userID
        referencedColumnName: id
        nullable: false
    deletedBy:
      targetEntity: AppBundle\Entity\User
      joinColumn:
        name: deletedBy
        referencedColumnName: id
        nullable: true
