AppBundle\Entity\ResultCache:
  type: entity
  table: result_cache
  options:
    collate: utf8mb4_unicode_ci
    charset: utf8mb4
  id:
    award:
      associationKey: true
    filter:
      type: string
      length: 40
      nullable: false
  fields:
    results:
      type: json_array
      nullable: false
    steps:
      type: json_array
      nullable: false
    warnings:
      type: json_array
      nullable: false
    votes:
      type: integer
      nullable: false
  manyToOne:
    award:
      targetEntity: Award
      inversedBy: resultCache
      joinColumn:
        name: awardID
        referencedColumnName: id
