AppBundle\Entity\TableHistory:
  type: entity
  table: table_history
  options:
    collate: utf8mb4_unicode_ci
    charset: utf8mb4
  id:
    id:
      type: integer
      nullable: false
      generator:
        strategy: AUTO
  fields:
    table:
      type: string
      nullable: false
      length: 30
      column: '`table`'
    entry:
      type: string
      nullable: false
      length: 255
    values:
      type: json_array
      nullable: false
      column: '`values`'
    timestamp:
      type: datetime
      nullable: false
  manyToOne:
    user:
      targetEntity: AppBundle\Entity\User
      joinColumn:
        name: userID
        referencedColumnName: steamID
        nullable: false
