AppBundle\Entity\UserInventoryItem:
  type: entity
  table: user_inventory_items
  id:
    id:
      type: integer
      nullable: false
      generator:
        strategy: AUTO
  fields:
    inventory:
      type: string
      length: 45
    timestamp:
      type: datetime
      nullable: false
  manyToOne:
    item:
      targetEntity: InventoryItem
      inversedBy: userItems
      joinColumn:
        name: itemID
        referencedColumnName: id
