<?php

namespace App\Security;

use App\Entity\AnonymousUser;
use RandomLib\Factory;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Http\Authenticator\AbstractAuthenticator;
use Symfony\Component\Security\Http\Authenticator\Passport\Badge\UserBadge;
use Symfony\Component\Security\Http\Authenticator\Passport\Passport;
use Symfony\Component\Security\Http\Authenticator\Passport\SelfValidatingPassport;

class AnonymousAuthenticator extends AbstractAuthenticator
{
    public function __construct(
        private string $secret,
        private readonly Security $security
    ) {
    }

    public function supports(Request $request): ?bool
    {
        // Don't run the authenticator if there's already a user
        $user = $this->security->getUser();
        if ($user) {
            return false;
        }

        return true;
    }

    public function authenticate(Request $request): Passport
    {
        $session = $request->getSession();

        // Generate a random ID to keep in the cookie if one doesn't already exist.
        // We use this cookie as part of the voting identification process.
        $randomIDCookie = $request->cookies->get('access');
        $randomIDSession = $session->get('access');

        if ($randomIDCookie && $randomIDSession) {
            $randomID = $randomIDCookie;
        } elseif ($randomIDCookie && !$randomIDSession) {
            $session->set('access', $randomIDCookie);
            $randomID = $randomIDCookie;
        } else {
            // Generate a random ID, then append it with a HMAC.
            // This allows us to verify that the ID was generated by us.
            // This has a very low security requirement, so we cut off the ID and HMAC at 16 characters each.
            $factory = new Factory;
            $generator = $factory->getLowStrengthGenerator();
            $randomID = substr(hash('sha256', $generator->generate(64)), 0, 16);
            $randomID .= ':' . substr(hash_hmac('md5', $randomID, $this->secret), 0, 16);

            $session->set('access', $randomID);
        }

        return new SelfValidatingPassport(new UserBadge($randomID, function ($identifier) {
            $user = new AnonymousUser();
            $user->setRandomID($identifier);
            return $user;
        }));
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token, string $firewallName): ?Response
    {
        return null;
    }

    public function onAuthenticationFailure(Request $request, AuthenticationException $exception): ?Response
    {
        return null;
    }
}
