App\Entity\Autocompleter:
  type: entity
  table: autocompleters
  options:
    collate: utf8mb4_unicode_ci
    charset: utf8mb4
  id:
    id:
      type: string
      length: 30
  fields:
    name:
      type: string
      nullable: false
      length: 20
    strings:
      type: json_array
      nullable: false
  oneToMany:
    awards:
      targetEntity: Award
      mappedBy: autocompleter
