App\Entity\Award:
  type: entity
  table: awards
  options:
    collate: utf8mb4_unicode_ci
    charset: utf8mb4
  id:
    id:
      type: string
      nullable: false
      length: 30
  fields:
    name:
      type: string
      nullable: false
      length: 100
    subtitle:
      type: string
      nullable: false
      length: 200
    order:
      type: integer
      nullable: false
      column: '`order`'
    comments:
      type: text
      nullable: true
    winnerImage:
      type: string
      nullable: true
      length: 255
    enabled:
      type: boolean
      nullable: false
    nominationsEnabled:
      type: boolean
      nullable: false
    secret:
      type: boolean
      nullable: false
      options:
        comment: 'Secret awards only show up during voting'
  manyToOne:
    autocompleter:
      targetEntity: Autocompleter
      inversedBy: awards
      joinColumn:
        name: autocompleteID
        referencedColumnName: id
        nullable: true
  oneToMany:
    feedback:
      targetEntity: AwardFeedback
      mappedBy: award
      cascade: ['remove']
    suggestions:
      targetEntity: AwardSuggestion
      mappedBy: award
      cascade: ['remove']
      orderBy: { 'suggestion': 'ASC' }
    nominees:
      targetEntity: Nominee
      mappedBy: award
      cascade: ['remove']
      orderBy: { 'name': 'ASC' }
    userNominations:
      targetEntity: UserNomination
      mappedBy: award
      cascade: ['remove']
    votes:
      targetEntity: Vote
      mappedBy: award
      cascade: ['remove']
    resultCache:
      targetEntity: ResultCache
      mappedBy: award
      cascade: ['remove']
