App\Entity\AwardSuggestion:
  type: entity
  table: award_suggestions
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    user:
      type: string
      nullable: false
      length: 45
    suggestion:
      type: string
      nullable: false
  manyToOne:
    award:
      targetEntity: Award
      inversedBy: suggestions
      joinColumn:
        name: awardID
        referencedColumnName: id
        nullable: true
