App\Entity\FantasyPrediction:
    type: entity
    table: fantasy_predictions
    id:
        id:
            type: integer
            nullable: false
            generator:
                strategy: AUTO
    fields:
        lastUpdated:
            type: datetime_immutable
    manyToOne:
        award:
            targetEntity: Award
            inversedBy: fantasyPredictions
        nominee:
            targetEntity: Nominee
            inversedBy: fantasyPredictions
        fantasyUser:
            targetEntity: FantasyUser
            inversedBy: predictions
