App\Entity\Permission:
  type: entity
  table: permissions
  options:
    collate: utf8mb4_unicode_ci
    charset: utf8mb4
  id:
    id:
      type: string
      nullable: false
      length: 40
  fields:
    description:
      type: string
      nullable: false
      length: 255
  manyToMany:
    children:
      targetEntity: Permission
      inversedBy: parents
      joinTable:
        name: permission_children
        joinColumns:
          parentID:
            referencedColumnName: id
        inverseJoinColumns:
          childID:
            referencedColumnName: id
    parents:
      targetEntity: Permission
      mappedBy: children
    users:
      targetEntity: User
      mappedBy: permissions
