App\Entity\UserNomination:
  type: entity
  table: user_nominations
  options:
    collate: utf8mb4_unicode_ci
    charset: utf8mb4
  id:
    id:
      type: integer
      nullable: false
      generator:
        strategy: AUTO
  fields:
    user:
      type: string
      nullable: false
      length: 45
    nomination:
      type: string
      nullable: false
      length: 255
    timestamp:
      type: datetime
      nullable: false
  manyToOne:
    award:
      targetEntity: Award
      inversedBy: userNominations
      joinColumn:
        name: awardID
        referencedColumnName: id
